AWSTemplateFormatVersion: 2010-09-09
Description: Template to start the visual search blog

Resources: 
  NotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType: ml.t3.medium
      RoleArn: !GetAtt Role.Arn
      DefaultCodeRepository: https://github.com/comdaze/sagemaker-visual-image-search

  Role:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        - PolicyName: CustomNotebookAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "es:ESHttp*"
                Resource:
                  - !Sub arn:aws-cn:es:${AWS::Region}:${AWS::AccountId}:domain/*
              - Effect: Allow
                Action: 
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:DeleteObject"
                  - "s3:PutObjectAcl"
                Resource:
                  - !Sub arn:aws-cn:s3:::${s3BucketTraining}/*
                  - !Sub arn:aws-cn:s3:::${s3BucketHosting}/*
      ManagedPolicyArns:
        - arn:aws-cn:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws-cn:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        - arn:aws-cn:iam::aws:policy/AWSCloudFormationReadOnlyAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - sagemaker.amazonaws.com
            Action:
              - 'sts:AssumeRole'
          
  s3BucketTraining:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls : false
        BlockPublicPolicy : false
        IgnorePublicAcls : false
        RestrictPublicBuckets : false

  s3BucketHosting:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls : false
        BlockPublicPolicy : false
        IgnorePublicAcls : false
        RestrictPublicBuckets : false
  Domain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Action: 'es:*'
            Resource: !Sub arn:aws-cn:es:${AWS::Region}:${AWS::AccountId}:domain/*/*
      ElasticsearchVersion: 7.4
      ElasticsearchClusterConfig:
        InstanceType: "t2.small.elasticsearch"
      EBSOptions:
        EBSEnabled: True
        VolumeSize: 10
        VolumeType: gp2


Outputs:
  esHostName:
    Description: Elasticsearch hostname 
    Value: !GetAtt Domain.DomainEndpoint

  esDomainName:
    Description: Elasticsearch domain name
    Value: !Ref Domain

  s3BucketTraining:
    Description: S3 bucket name for training
    Value: !Ref s3BucketTraining

  s3BucketHostingBucketName:
    Description: S3 bucket name for frontend hosting
    Value: !Ref s3BucketHosting
  WebsiteURL:
    Value: !GetAtt 
      - s3BucketHosting
      - WebsiteURL
    Description: URL for website hosted on S3

  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - s3BucketHosting
          - Domain Name
    Description: Name of S3 bucket to hold website content

  SageMakerNotebookURL:
    Description: SageMaker Notebook Instance
    Value: !Join 
      - ''
      - - 'https://console.amazonaws.cn/sagemaker/home?region=cn-northwest-1#/notebook-instances/openNotebook/'
        - !GetAtt NotebookInstance.NotebookInstanceName
        - '?view=lab'